spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/uzummarket

  cache:
    redis:
      time-to-live: 30m
      enable-statistics: true
  data:
    redis:
      host: localhost
      port: 6379
      password: root123


  profiles:
    active: prod

jwt:
  access:
    token:
      #      expiry: 600000 # 10 minutes
      expiry: 6000000 # 10+.. minutes
      secret:
        key: 357638792F423F4528482B4D6250655368566D597133743677397A24432646294A404E635266546A576E5A7234753778214125442A472D4B6150645367566B58
  refresh:
    token:
      expiry: 864000000 # 10 days
      secret:
        key: 7134743777217A25432A462D4A614E645267556B58703272357538782F413F44

management:
  endpoint:
    health:
      show-details: always
    startup:
      enabled: true


  health:
    diskspace:
      enabled: true
      threshold: 1GB

  endpoints:
    web:
      exposure:
        include: '*'
cloud:
  aws:
    stack:
      auto: false
    bucket:
      name: 'qovunmarket'
    credentials:
      access-key: 'AKIAV2VDW3ICSX4DGHSP'
      secret-key: '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'
    region:
      static: ap-south-1
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080


logging:
  level:
    root: info
    org:
      springframework:
        web:
          client:
            RestTemplate: debug
      zalando:
        logbook: TRACE
logbook:
  exclude:
    - '/api/upload'
    - '/api/download'

